sonar.verbose=true

sonar.organization=shwetaraut815-key
sonar.projectKey=shwetaraut815-key_saidemytrend
sonar.projectName=saidemtrend

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
