sonar.verbose=true

sonar.organization=saidemv01-keeyy
sonar.projectKey=saidemv01-keeyy_saidemytrend
sonar.projectName=saidemtrend

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
